---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eck-stack.fullname" . }}-fluentd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eck-stack.fullname" . }}-fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "eck-stack.fullname" . }}-fluentd
roleRef:
  kind: ClusterRole
  name: {{ include "eck-stack.fullname" . }}-fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "eck-stack.fullname" . }}-fluentd
  namespace: logging