apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eck-stack.fullname" . }}-kibana-import
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: kibana-data
        configMap:
            name: kibana-data
            defaultMode: 0777
      containers:
      - name: kibana-import
        image: couchbase/centos7-systemd
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_PROTOCOL
          {{- if .Values.kibana.http.tls.disabled }}
          value: http
          {{- else }}     
          value: https      
          {{- end }}
        - name: KIBANA_URL
          value: {{ include "eck-stack.fullname" . }}-{{ .Values.kibana.service.name }}-kb-http
        - name: KIBANA_PORT
          value: "{{ .Values.kibana.service.port }}"
        - name: ELASTIC_USER
          value: "elastic"
        - name: ELASTIC_PWD
          valueFrom:
            secretKeyRef:
              name: {{ include "eck-stack.fullname" . }}-elasticsearch-es-elastic-user
              key: elastic
        command: ["/bin/sh","/kibana/curl-script.sh"]
        volumeMounts:
        - name: kibana-data
          mountPath: /kibana/